# Application information
server.port: 8080

# Logging properties
logging.file: measurementService.log
server.tomcat.basedir: target/tomcat
server.tomcat.access_log_enabled: true
server.tomcat.access_log_pattern: '%h %t "%r" %s %b'

# Version & debug information
info.app.name: Paraconsistente
info.app.description: Testar o software de paraconsistente do Prof. Luiz
info.app.version: 1.0
